services:
  jetson-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: jetson-dev
    # Opting for aarch64 image, x86_64 available but will cause python wheel difficulties
    platform: linux/arm64
    volumes:
      - .:/workspaces/repo:cached
      # Mount target sysroot and dependency overlay
      - ./sysroots/r36.4.4:/opt/jetson-sysroot:cached
      - ./third_party/r36.4.4-overlay:/opt/jetson-sysroot-overlay:cached
    working_dir: /workspaces/repo
    tty: true
    stdin_open: true
