# ---- Build bundle for target ----
if(NOT DEFINED EDGEVISION_OVERLAY_ROOT)
    message(FATAL_ERROR "EDGEVISION_OVERLAY_ROOT is not set")
endif()
if(NOT DEFINED EDGEVISION_BUNDLE_DIR)
    message(FATAL_ERROR "EDGEVISION_BUNDLE_DIR is not set")
endif()
if(NOT DEFINED EDGEVISION_BINARY)
    message(FATAL_ERROR "EDGEVISION_BINARY is not set")
endif()
if(NOT DEFINED EDGEVISION_EXTRA_BINARIES)
    set(EDGEVISION_EXTRA_BINARIES "")
endif()

# Install dir of deps
set(EDGEVISION_INSTALL_DIR "${EDGEVISION_OVERLAY_ROOT}/install")

# ---- Handle setting RPATH values ----
function(_edgevision_set_bundle_rpath file_path)
    if(NOT UNIX OR APPLE)
        return()
    endif()

    find_program(_edgevision_objdump NAMES objdump llvm-objdump)
    if(NOT _edgevision_objdump)
        message(STATUS "Skipping RPATH rewrite for '${file_path}': no objdump tool available")
        return()
    endif()

    execute_process(
        COMMAND "${_edgevision_objdump}" -p "${file_path}"
        OUTPUT_VARIABLE _edgevision_objdump_output
        ERROR_QUIET
        RESULT_VARIABLE _edgevision_objdump_result
    )

    if(_edgevision_objdump_result EQUAL 0 AND _edgevision_objdump_output MATCHES "(RPATH|RUNPATH)")
        file(RPATH_SET FILE "${file_path}" NEW_RPATH "\$ORIGIN/../lib")
    elseif(_edgevision_objdump_result EQUAL 0)
        message(STATUS "Skipping RPATH rewrite for '${file_path}': no existing ELF RPATH/RUNPATH entry")
    else()
        message(STATUS "Skipping RPATH rewrite for '${file_path}': failed to inspect binary with objdump")
    endif()
endfunction()

file(MAKE_DIRECTORY "${EDGEVISION_BUNDLE_DIR}/bin")
file(MAKE_DIRECTORY "${EDGEVISION_BUNDLE_DIR}/lib")
file(MAKE_DIRECTORY "${EDGEVISION_BUNDLE_DIR}/tests")

if(EXISTS "${EDGEVISION_BINARY}")
    file(COPY "${EDGEVISION_BINARY}" DESTINATION "${EDGEVISION_BUNDLE_DIR}/bin")
    get_filename_component(_edgevision_bin_name "${EDGEVISION_BINARY}" NAME)
    set(_edgevision_bundle_bin "${EDGEVISION_BUNDLE_DIR}/bin/${_edgevision_bin_name}")
    _edgevision_set_bundle_rpath("${_edgevision_bundle_bin}")
else()
    message(FATAL_ERROR "EdgeVision binary not found at ${EDGEVISION_BINARY}")
endif()

foreach(_extra_bin IN LISTS EDGEVISION_EXTRA_BINARIES)
    if(EXISTS "${_extra_bin}")
        file(COPY "${_extra_bin}" DESTINATION "${EDGEVISION_BUNDLE_DIR}/tests")
        get_filename_component(_extra_bin_name "${_extra_bin}" NAME)
        set(_extra_bundle_bin "${EDGEVISION_BUNDLE_DIR}/tests/${_extra_bin_name}")
        _edgevision_set_bundle_rpath("${_extra_bundle_bin}")
    else()
        message(FATAL_ERROR "Extra binary not found at ${_extra_bin}")
    endif()
endforeach()

set(_tests_cmake_dir "${EDGEVISION_BUNDLE_DIR}/tests")
set(_ctest_file "${_tests_cmake_dir}/CTestTestfile.cmake")
set(_dollar "$")
file(WRITE "${_ctest_file}" "# CTest test file generated by bundle.cmake\n")
file(APPEND "${_ctest_file}" "set(CTEST_RESOURCE_SPEC_FILE \"\")\n")
foreach(_extra_bin IN LISTS EDGEVISION_EXTRA_BINARIES)
    if(EXISTS "${_extra_bin}")
        get_filename_component(_extra_bin_name "${_extra_bin}" NAME)
        file(APPEND "${_ctest_file}" "add_test(${_extra_bin_name} \"${_dollar}{CTEST_FILE_DIR}/${_extra_bin_name}\")\n")
    endif()
endforeach()

if(EXISTS "${EDGEVISION_INSTALL_DIR}/lib")
    file(COPY "${EDGEVISION_INSTALL_DIR}/lib" DESTINATION "${EDGEVISION_BUNDLE_DIR}")
endif()
if(EXISTS "${EDGEVISION_INSTALL_DIR}/lib64")
    file(COPY "${EDGEVISION_INSTALL_DIR}/lib64" DESTINATION "${EDGEVISION_BUNDLE_DIR}")
endif()
if(EXISTS "${CMAKE_SOURCE_DIR}/../cmake/suppressions" AND ${CMAKE_BUILD_TYPE} EQUAL "Debug")
    file(MAKE_DIRECTORY "${EDGEVISION_BUNDLE_DIR}/cmake")
    file(COPY "${CMAKE_SOURCE_DIR}/../cmake/suppressions" DESTINATION "${EDGEVISION_BUNDLE_DIR}/cmake")
endif()

